#!/bin/bash

echo ""
echo " ============================================== "
echo "  If you want to download private artifacts     "
echo "  from TaskCluster, please get your temporary   "
echo "  credentials from:                             "
echo "  https://auth.taskcluster.net/                 "
echo "                                                "
echo "  You can put the credentials into              "
echo "  'tc_credentials.json' file under your home    "
echo "  directory. see more detail:                   "
echo "  https://pypi.python.org/pypi/taskcluster_util "
echo " ============================================== "
echo ""
